export default [
  {
    date: "01/05/2024",
    name: "Marie Dupont",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "2 mois",
    financialNote: 74,
    creditNote: 89,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "02/05/2024",
    name: "Jean Martin",
    rev: "ACR",
    address: "France",
    payment: "Virement",
    deadline: "1 semaine",
    financialNote: 65,
    creditNote: 92,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "03/05/2024",
    name: "Sophie Bernard",
    rev: "ACR",
    address: "France",
    payment: "Paypal",
    deadline: "6 jours",
    financialNote: 88,
    creditNote: 77,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "04/05/2024",
    name: "Éric Petit",
    rev: "ACR",
    address: "France",
    payment: "Chèque",
    deadline: "3 mois",
    financialNote: 53,
    creditNote: 63,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "05/05/2024",
    name: "Lucie Richard",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "2 semaines",
    financialNote: 90,
    creditNote: 95,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "06/05/2024",
    name: "Pierre Durand",
    rev: "ACR",
    address: "France",
    payment: "Virement",
    deadline: "5 jours",
    financialNote: 60,
    creditNote: 70,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "07/05/2024",
    name: "Chloé Lefevre",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "1 mois",
    financialNote: 85,
    creditNote: 80,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "08/05/2024",
    name: "Vincent Moreau",
    rev: "ACR",
    address: "France",
    payment: "Chèque",
    deadline: "4 semaines",
    financialNote: 72,
    creditNote: 76,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "09/05/2024",
    name: "Émilie Simon",
    rev: "ACR",
    address: "France",
    payment: "Paypal",
    deadline: "7 jours",
    financialNote: 68,
    creditNote: 82,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "10/05/2024",
    name: "Julien Michel",
    rev: "ACR",
    address: "France",
    payment: "Virement",
    deadline: "3 mois",
    financialNote: 78,
    creditNote: 90,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "11/05/2024",
    name: "Isabelle Leroy",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "2 jours",
    financialNote: 83,
    creditNote: 94,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "12/05/2024",
    name: "Marc Roux",
    rev: "ACR",
    address: "France",
    payment: "Chèque",
    deadline: "1 semaine",
    financialNote: 71,
    creditNote: 69,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "13/05/2024",
    name: "Laure David",
    rev: "ACR",
    address: "France",
    payment: "Paypal",
    deadline: "6 mois",
    financialNote: 62,
    creditNote: 75,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "14/05/2024",
    name: "Stéphane Vincent",
    rev: "ACR",
    address: "France",
    payment: "Virement",
    deadline: "5 semaines",
    financialNote: 57,
    creditNote: 67,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "15/05/2024",
    name: "Aurélie Adam",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "10 jours",
    financialNote: 91,
    creditNote: 88,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "06/05/2024",
    name: "Pierre Durand",
    rev: "ACR",
    address: "France",
    payment: "Virement",
    deadline: "5 jours",
    financialNote: 60,
    creditNote: 70,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "07/05/2024",
    name: "Chloé Lefevre",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "1 mois",
    financialNote: 85,
    creditNote: 80,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "08/05/2024",
    name: "Vincent Moreau",
    rev: "ACR",
    address: "France",
    payment: "Chèque",
    deadline: "4 semaines",
    financialNote: 72,
    creditNote: 76,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "09/05/2024",
    name: "Émilie Simon",
    rev: "ACR",
    address: "France",
    payment: "Paypal",
    deadline: "7 jours",
    financialNote: 68,
    creditNote: 82,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "10/05/2024",
    name: "Julien Michel",
    rev: "ACR",
    address: "France",
    payment: "Virement",
    deadline: "3 mois",
    financialNote: 78,
    creditNote: 90,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "11/05/2024",
    name: "Isabelle Leroy",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "2 jours",
    financialNote: 83,
    creditNote: 94,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "12/05/2024",
    name: "Marc Roux",
    rev: "ACR",
    address: "France",
    payment: "Chèque",
    deadline: "1 semaine",
    financialNote: 71,
    creditNote: 69,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "13/05/2024",
    name: "Laure David",
    rev: "ACR",
    address: "France",
    payment: "Paypal",
    deadline: "6 mois",
    financialNote: 62,
    creditNote: 75,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "14/05/2024",
    name: "Stéphane Vincent",
    rev: "ACR",
    address: "France",
    payment: "Virement",
    deadline: "5 semaines",
    financialNote: 57,
    creditNote: 67,
    recoveryPlan: "non",
    status: "info prix",
  },
  {
    date: "15/05/2024",
    name: "Aurélie Adam",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "10 jours",
    financialNote: 91,
    creditNote: 88,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "15/05/2024",
    name: "Aurélie Adam",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "10 jours",
    financialNote: 91,
    creditNote: 88,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "15/05/2024",
    name: "Aurélie Adam",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "10 jours",
    financialNote: 91,
    creditNote: 88,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "15/05/2024",
    name: "Aurélie Adam",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "10 jours",
    financialNote: 91,
    creditNote: 88,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "15/05/2024",
    name: "Aurélie Adam",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "10 jours",
    financialNote: 91,
    creditNote: 88,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "15/05/2024",
    name: "Aurélie Adam",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "10 jours",
    financialNote: 91,
    creditNote: 88,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "15/05/2024",
    name: "Aurélie Adam",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "10 jours",
    financialNote: 91,
    creditNote: 88,
    recoveryPlan: "oui",
    status: "info prix",
  },
  {
    date: "15/05/2024",
    name: "Souheib",
    rev: "ACR",
    address: "France",
    payment: "Carte",
    deadline: "10 jours",
    financialNote: 91,
    creditNote: 88,
    recoveryPlan: "oui",
    status: "info prix",
  },
];
